### ISSUE TITLE
Let methods in shellcraft be documented

### ISSUE THREAD

**Issue by david942j** [peter50216/pwntools-ruby#46]
Currently all files under shellcraft/templates cannot be documented.
Need redesign the shellcraft module to do so.

Features we want for shellcraft are listed as follows(so we can make sure our new design fulfills them):
1. Support multi-architecture (currently i386/amd64).
1. When one invokes `shellcraft.sh`, it would find the correct assembly according to context.arch.
1. All public methods are documented.
1. Since there are many common codes between these two architecture, we need DRY (currently we use x86 directory to achieve this)
1. Don't be confused between `shellcraft.connect` and `shellcraft.syscall.connect`, which was a bug in pwntools-python.
1. [Discuss] Do we really need to support something like `shellcraft.i386.linux.sh` under amd64 context? One can use `context.local` to achieve calling another architecture's assemblies.

**Comment by david942j** [comment]
Need suggestions @peter50216 @ShikChen @hanhanW

**Comment by peter50216** [comment]
I would say no for the last point.

**Comment by david942j** [comment]
I think the main problem is the 'module' in python is separated by '.', i.e. `shellcraft.amd64.linux.sh()`
While in ruby style it should be `Shellcraft::Amd64::Linux.sh`
But the ruby one is hard for typing.

I suggested that we define methods in ruby way:
```rb
# amd64/common/common.rb
module ::Pwnlib::Shellcraft::Amd64
  # document goes here
  module Common
     # defines method `cat`
     include Pwnlib::Shellcraft::Helper
  end
end

# amd64/common/mov.rb
module ::Pwnlib::Shellcraft::Amd64::Common
  # document goes here
  def mov(src, dst)
     # ...
     cat "mov #{src}, #{dst}"
  end
end

# amd64/linux/sh.rb
module ::Pwnlib::Shellcraft::Amd64::Linux
  # document goes here
  def sh(*args)
     context.local(arch: 'amd64') do
        cat Shellcraft::X86::Linux.sh(*args)
     end
  end
end

```

And add an instance `shellcraft` that defines all methods like `shellcraft.amd64.common.mov`, `shellcraft.amd64.linux.sh`
And it adopts calls like `shellcraft.${arch}.(common|${os}).xx` to be abbreviated to `shellcraft.xx`
